### ISSUE TITLE
Plugin doesnt work with newest sketch anymore

### ISSUE THREAD

**Issue by qimmiq** [mathieudutour/import-svg-as-artboard#3]
my loved plugin doenst do the job with latest sketch update (Version 61.2 (89653))
i hope there is a fix for it ?!

**Comment by qimmiq** [comment]
`TypeError: s.prepareToImportFromURL is not a function. (In 's.prepareToImportFromURL(NSURL.fileURLWithPath(n))', 's.prepareToImportFromURL' is undefined)
    at /Users/nberg/ownCloud/Mackup/Library/Application Support/com.bohemiancoding.sketch3/Plugins/import-svg-as-artboard.sketchplugin/Contents/Sketch/my-command.js:37:571
    at forEach[native code] (/)`

**Comment by PeakXing** [comment]
Please fix~
